def usage_text():
    return ("Usage:\r\n"
   "python3 scripts.py A"
   "RG\r\n\r\n"
   "dev             buil"
   "d and run project\r"
   "\n"
   "build           buil"
   "d: python3 scripts.p"
   "y build debug or pyt"
   "hon3 scripts.py buil"
   "d release\r\n"
   "run             run "
   "project\r\n"
   "debug           run "
   "gdb on project\r\n"
   "rename ARG2     rena"
   "me project, ARG2 is "
   "new name no spaces\r"
   "\n"
   "santize         use "
   "build using address-"
   "sanitzer\r\n"
   "test            buil"
   "ds and runs GTests i"
   "n tests dir\r\n"
   "benchmark       runs"
   " benchmark on releas"
   "e version of project"
   "\r\n"
   "prod            buil"
   "ds to release, sanit"
   "izes, tests and benc"
   "hmarks\r\n\r\n"
   "edit conanfile.txt t"
   "o add packages")
def title_text():
    return ("\r\n"
   " __    __     _     "
   "                    "
   "   _                "
   "              _     "
   "                    "
   "                    "
   "         \r\n"
   "/ / /\\ \\ \\___| | "
   "___ ___  _ __ ___   "
   "___  | |_ ___     __"
   "_ _ __ ___  __ _| |_"
   " ___        ___ _ __"
   "  _ __         __ _ "
   "_ __  _ __  \r\n"
   "\\ \\/  \\/ / _ \\ |"
   "/ __/ _ \\| \'_ ` _ "
   "\\ / _ \\ | __/ _ \\"
   "   / __| \'__/ _ \\/"
   " _` | __/ _ \\_____ "
   "/ __| \'_ \\| \'_ \\"
   " _____ / _` | \'_ \\"
   "| \'_ \\ \r\n"
   " \\  /\\  /  __/ | ("
   "_| (_) | | | | | |  "
   "__/ | || (_) | | (__"
   "| | |  __/ (_| | || "
   " __/_____| (__| |_) "
   "| |_) |_____| (_| | "
   "|_) | |_) |\r\n"
   "  \\/  \\/ \\___|_|"
   "\\___\\___/|_| |_| |"
   "_|\\___|  \\__\\___/"
   "   \\___|_|  \\___|"
   "\\__,_|\\__\\___|   "
   "   \\___| .__/| .__/"
   "       \\__,_| .__/|"
   " .__/ \r\n"
   "                    "
   "                    "
   "                    "
   "                    "
   "            |_|   |_"
   "|               |_| "
   "  |_|    \r\n");