def usage_text():
    return ("Usage:\r\n"
   "python3 scripts.py A"
   "RG\r\n\r\n"
   "dev             buil"
   "d and run project\r"
   "\n"
   "build           buil"
   "d: python3 scripts.p"
   "y build debug or pyt"
   "hon3 scripts.py buil"
   "d release\r\n"
   "run             run "
   "project\r\n"
   "debug           run "
   "gdb on project\r\n"
   "rename ARG2     rena"
   "me project, ARG2 is "
   "new name no spaces\r"
   "\n"
   "santize         use "
   "build using address-"
   "sanitzer\r\n"
   "test            buil"
   "ds and runs GTests i"
   "n tests dir\r\n"
   "benchmark       runs"
   " benchmark on releas"
   "e version of project"
   "\r\n"
   "prod            buil"
   "ds to release, sanit"
   "izes, tests and benc"
   "hmarks\r\n\r\n"
   "edit conanfile.txt t"
   "o add packages")
